//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookyourdoctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital_request
    {
        public System.DateTime Hospital_start_time { get; set; }
        public System.DateTime hospital_end_time { get; set; }
        public string patient_name { get; set; }
        public string Hospital_day { get; set; }
        public int id { get; set; }
        public string doctor_id { get; set; }
    }
}
